import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

IshaDF = pd.read_csv('Isha - RS23_30.csv')
DebDF = pd.read_csv('Deb - RS23_30.csv')
LioraDF = pd.read_csv('Liora - RS23_30.csv')
TaimingDF = pd.read_csv('Taiming - RS23_30.csv')
AvvaDF = pd.read_csv('Avva - RS23_30.csv')

IshaDF1 = pd.read_csv('Isha - RS23_1.csv')
DebDF1 = pd.read_csv('Deb - RS23_1.csv')
LioraDF1 = pd.read_csv('Liora - RS23_1.csv')
TaimingDF1 = pd.read_csv('Taiming - RS23_1.csv')
AvvaDF1 = pd.read_csv('Avva - RS23_1.csv')

DF2330 = pd.read_csv('RS23_30.csv')
DF030 = pd.read_csv('RS0_30.csv')
DF4230 = pd.read_csv('RS42_30.csv')

plt.plot(DF2330['Sample Fraction'], DF2330['pos dif'], label = 'Random_State 23' )
plt.plot(DF030['Sample Fraction'], DF030['pos dif'], label = 'Random_State 0')
plt.plot(DF4230['Sample Fraction'], DF4230['pos dif'], label = 'Random_State 42')
plt.title("Regression for |user_pos - stim_pos|: 5-fold means for Subject 30")
plt.xlabel("Sample Fraction", fontsize=15)
plt.ylabel("R2 Score", fontsize=15)
plt.ylim(0,None)
plt.legend()
plt.show()

plt.plot(DF2330['Sample Fraction'], DF2330['pos'], label = 'Random_State 23' )
plt.plot(DF030['Sample Fraction'], DF030['pos'], label = 'Random_State 0')
plt.plot(DF4230['Sample Fraction'], DF4230['pos'], label = 'Random_State 42')
plt.title("Regression for |stim_pos|: 5-fold means for Subject 30")
plt.xlabel("Sample Fraction", fontsize=15)
plt.ylabel("R2 Score", fontsize=15)
plt.ylim(0,None)
plt.legend()
plt.show()

plt.plot(DF2330['Sample Fraction'], DF2330['speed'], label = 'Random_State 23' )
plt.plot(DF030['Sample Fraction'], DF030['speed'], label = 'Random_State 0')
plt.plot(DF4230['Sample Fraction'], DF4230['speed'], label = 'Random_State 42')
plt.title("Regression for |change_rate_x|: 5-fold means for Subject 30")
plt.xlabel("Sample Fraction", fontsize=15)
plt.ylabel("R2 Score", fontsize=15)
plt.ylim(0,None)
plt.legend()
plt.show()

plt.plot(IshaDF1['Sample Fraction'], IshaDF1['pos dif'], label = 'Isha' )
plt.plot(DebDF1['Sample Fraction'], DebDF1['pos dif'], label = 'Deborah')
plt.plot(LioraDF1['Sample Fraction'], LioraDF1['pos dif'], label = 'Liora')
plt.plot(TaimingDF1['Sample Fraction'], TaimingDF1['pos dif'], label = 'Taiming')
plt.plot(AvvaDF1['Sample Fraction'], AvvaDF1['pos dif'], label = 'Avva')
plt.title("Regression for |user_pos - stim_pos|: 5-fold means (RS = 23) for Subject 1")
plt.xlabel("Sample Fraction", fontsize=15)
plt.ylabel("R2 Score", fontsize=15)
plt.ylim(0,None)
plt.legend()
plt.show()

plt.plot(IshaDF['Sample Fraction'], IshaDF['pos'], label = 'Isha' )
plt.plot(DebDF['Sample Fraction'], DebDF['pos'], label = 'Deborah')
plt.plot(LioraDF['Sample Fraction'], LioraDF['pos'], label = 'Liora')
plt.plot(TaimingDF['Sample Fraction'], TaimingDF['pos'], label = 'Taiming')
plt.plot(AvvaDF['Sample Fraction'], AvvaDF['pos'], label = 'Avva')
plt.title("Regression for |stim_pos|: 5-fold means (RS = 23) for Subject 30")
plt.xlabel("Sample Fraction", fontsize=15)
plt.ylabel("R2 Score", fontsize=15)
plt.ylim(0,None)
plt.legend()
plt.show()


plt.plot(IshaDF1['Sample Fraction'], IshaDF1['speed'], label = 'Isha' )
plt.plot(DebDF1['Sample Fraction'], DebDF1['speed'], label = 'Deborah')
plt.plot(LioraDF1['Sample Fraction'], LioraDF1['speed'], label = 'Liora')
plt.plot(TaimingDF1['Sample Fraction'], TaimingDF1['speed'], label = 'Taiming')
plt.plot(AvvaDF1['Sample Fraction'], AvvaDF1['speed'], label = 'Avva')
plt.title("Regression for |change_rate_x|: 5-fold means (RS = 23) for Subject 1")
plt.xlabel("Sample Fraction", fontsize=15)
plt.ylabel("R2 Score", fontsize=15)
plt.ylim(0,None)
plt.legend()
plt.show()